---
deployment:
 tasks:
 - export DEPLOYPATH=/home/accesshe/public_html
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp accessable-bathrooms.html $DEPLOYPATH
 - /bin/cp garage-conversions.html $DEPLOYPATH
 - /bin/cp grants.html $DEPLOYPATH
 - /bin/cp occupational-therapist.html $DEPLOYPATH
 - /bin/cp ramps-and-saftey-rails.html $DEPLOYPATH
 - /bin/cp stairlifts.html $DEPLOYPATH
 - /bin/cp -r assets $DEPLOYPATH
 - /bin/cp -r forms $DEPLOYPATH
    